### ISSUE TITLE
lock on to sever line 590

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [alexiswl/poreduck#2]
I got the following error python transfer_fast5_to_server.py --reads_dir /home/poretools/data/Lanfearlab/Volumes/LANFEARSEQ3/1003_Miriam_data_uploaded --server_name raijin.nci.org.au --dest_directory /short/xf3/bxs800/MinIon/transfer_test --user_name bxs800 --sample_name EG_AB_D
password: 
('PING raijin.nci.org.au (192.43.239.23) 56(84) bytes of data.\n64 bytes from raijin3.nci.org.au (192.43.239.23): icmp_seq=1 ttl=60 time=0.661 ms\n\n--- raijin.nci.org.au ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 0.661/0.661/0.661/0.000 ms\n', '')
'Pertt'
Traceback (most recent call last):
  File "transfer_fast5_to_server.py", line 661, in <module>
    main()
  File "transfer_fast5_to_server.py", line 89, in main
    check_directories()
  File "transfer_fast5_to_server.py", line 590, in check_directories
    if not s.login(SERVER_NAME, SERVER_USERNAME, PASSWORD):
  File "/home/poretools/anaconda3/envs/poretools/lib/python2.7/site-packages/pexpect/pxssh.py", line 336, in login
    raise ExceptionPxssh('could not synchronize with original prompt')
pexpect.pxssh.ExceptionPxssh: could not synchronize with original prompt

after some digging I set the original_prompt='pwd' in s (pxssh.pxssh) instead of the '[#$]'. The later appears to throw an error on raijin. 

Same in line 475.

**Comment by alexiswl** [comment]
Hi Ben, I have added the no-sshpass option and added a mini-tutorial on how to generate a authenication key and add it to a server. I am yet to configure the add lock-file and remove lock-file scripts such that they can be completed without a password. I'm not sure if it would fix this though, which may be due to the bash_profile spitting the cwd into stdout?

Alexis.
