### ISSUE TITLE
Transferring to server produces "Error, parent directory of *** does not exist"

### ISSUE THREAD

**Issue by danarte** [alexiswl/poreduck#5]
After almost a full day of fiddling I was able to run transfer_fast5_to_server.py without any errors of missing dependencies. Though, when running the command with all the options I was met with an error. 

When I run the command it immediately displays a big block of text (first part) and after a second or two it displays the another text block with a clear indication of an error.
Here is the error (as it's displayed in cygwin, I guess the error part is in the second part of output):
First part
```
artem@MinION-PC ~
$ ./poreduck/transfer_fast5_to_server.py  --reads_dir /cygdrive/f/data/reads --
server_name nshomron --user_name artemd --dest_directory '/groups/nshomron/arte
md/tmp/minion/AlbacoreTest'  --sample_name Lambda_Lib7
password:
("Bad option -c.\r\n\r\n\r\nUsage: ping [-t] [-a] [-n count] [-l size] [-f] [-i
TTL] [-v TOS]\r\n            [-r count] [-s count] [[-j host-list] | [-k host-li
st]]\r\n            [-w timeout] [-R] [-S srcaddr] [-4] [-6] target_name\r\n\r\n
Options:\r\n    -t             Ping the specified host until stopped.\r\n
            To see statistics and continue - type Control-Break;\r\n
       To stop - type Control-C.\r\n    -a             Resolve addresses to host
names.\r\n    -n count       Number of echo requests to send.\r\n    -l size
    Send buffer size.\r\n    -f             Set Don't Fragment flag in packet (I
Pv4-only).\r\n    -i TTL         Time To Live.\r\n    -v TOS         Type Of Ser
vice (IPv4-only. This setting has been deprecated\r\n                   and has
no effect on the type of service field in the IP Header).\r\n    -r count
Record route for count hops (IPv4-only).\r\n    -s count       Timestamp for cou
nt hops (IPv4-only).\r\n    -j host-list   Loose source route along host-list (I
Pv4-only).\r\n    -k host-list   Strict source route along host-list (IPv4-only)
.\r\n    -w timeout     Timeout in milliseconds to wait for each reply.\r\n    -
R             Use routing header to test reverse route also (IPv6-only). \r\n
 -S srcaddr     Source address to use.\r\n    -4             Force using IPv4.\r
\n    -6             Force using IPv6.\r\n\r\n", '')
```
Second part
```
SSH passed
('/groups/nshomron/artemd/tmp', 'if [ -d /groups/nshomron/artemd/tmp ]; then ech
o "PRESENT"; fi\r\r\nif: Expression Syntax.\r\n')
Error, parent directory of /groups/nshomron/artemd/tmp/minion/AlbacoreTest does
not exist
```

Hope you can help me solve it because it would be unfortunate to throw away all the time spent on the setup.

Thanks.

**Comment by alexiswl** [comment]
Hi there,

I am sorry to hear that you are having trouble and thank you for the time to reach out.

Would you mind trying the following in Cygwin and providing me with the output.
`ping nshomron`

And then ssh into nshomron and type the following
`if [ -d /groups/nshomron/artemd/tmp ];  then echo "PRESENT";  fi`
and check the output

Also would you mind trying with
Destination directory set to: 
`--dest_directory '/groups/nshomron/artemd/tmp/minion/AlbacoreTest/'`
rather than
`'/groups/nshomron/artemd/tmp/minion/AlbacoreTest'`
At the moment I have used some poor practise with regards to getting the parent directory as I was unsure of os.path.join would work over a server.

In light of not being able to produce this error (because my Cygwin would not let me use pexpect) I believe it might be appropriate to move to paramiko for this stage of the script. 
I have since added paramiko compatibility. Please let me know if you continue to have issues.

**Comment by danarte** [comment]
Hi,
Pinging the server was fine, and after connecting to it and running the command "if[ -d....." I understood that there could be an error because the default shell is tcsh, so I changed it to bash for the purpose of this script.
I then encountered yet another error, here is the output:
```
artem@MinION-PC ~
$ ./poreduck/transfer_fast5_to_server.py  --reads_dir /cygdrive/f/data/reads --
server_name nshomron --user_name artemd --dest_directory '/groups/nshomron/arte
md/tmp/minion/AlbacoreTest/'  --sample_name Lambda_Lib7
password:
("Bad option -c.\r\n\r\n\r\nUsage: ping [-t] [-a] [-n count] [-l size] [-f] [-i
TTL] [-v TOS]\r\n            [-r count] [-s count] [[-j host-list] | [-k host-li
st]]\r\n            [-w timeout] [-R] [-S srcaddr] [-4] [-6] target_name\r\n\r\n
Options:\r\n    -t             Ping the specified host until stopped.\r\n
            To see statistics and continue - type Control-Break;\r\n
       To stop - type Control-C.\r\n    -a             Resolve addresses to host
names.\r\n    -n count       Number of echo requests to send.\r\n    -l size
    Send buffer size.\r\n    -f             Set Don't Fragment flag in packet (I
Pv4-only).\r\n    -i TTL         Time To Live.\r\n    -v TOS         Type Of Ser
vice (IPv4-only. This setting has been deprecated\r\n                   and has
no effect on the type of service field in the IP Header).\r\n    -r count
Record route for count hops (IPv4-only).\r\n    -s count       Timestamp for cou
nt hops (IPv4-only).\r\n    -j host-list   Loose source route along host-list (I
Pv4-only).\r\n    -k host-list   Strict source route along host-list (IPv4-only)
.\r\n    -w timeout     Timeout in milliseconds to wait for each reply.\r\n    -
R             Use routing header to test reverse route also (IPv6-only). \r\n
 -S srcaddr     Source address to use.\r\n    -4             Force using IPv4.\r
\n    -6             Force using IPv6.\r\n\r\n", '')
SSH passed
('/groups/nshomron/artemd/tmp/minion', 'if [ -d /groups/nshomron/artemd/tmp/mini
on ]; then echo "PRESENT"; f\r\n\ri\r\nPRESENT\r\n')
if [ ! -d /groups/nshomron/artemd/tmp/minion/AlbacoreTest/ ]; then m
kdir /groups/nshomron/artemd/tmp/minion/AlbacoreTest/; fi

SSH passed
Traceback (most recent call last):
  File "./poreduck/transfer_fast5_to_server.py", line 702, in <module>
    main()
  File "./poreduck/transfer_fast5_to_server.py", line 101, in main
    create_transferring_lock_file()  # Indicator for down-the-line base
  File "./poreduck/transfer_fast5_to_server.py", line 523, in create_transferrin
g_lock_file
    s.logout()  # Logout
  File "/usr/lib/python2.7/site-packages/pexpect/pxssh.py", line 353, in logout
    index = self.expect([EOF, "(?i)there are stopped jobs"])
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 321, in exp
ect
    timeout, searchwindowsize, async)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 345, in exp
ect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect
_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout

    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pxssh.pxssh object at 0x6ffffbe5510>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-q', '-l', 'artemd', 'nshomron']
buffer (last 100 chars): 'exit\r\nexit\r\n[artemd@nshomron ~]$ '
before (last 100 chars): 'exit\r\nexit\r\n[artemd@nshomron ~]$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 7208
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: EOF
    1: re.compile("(?i)there are stopped jobs")
```

**Comment by alexiswl** [comment]
Excuse my ignorance, I was not aware (thus nor considerate) of non bash shells. I have added 'bash -c' to the start of each of the required commands to force bash scripting.

As for the albacore_server_scaled.py 'not finding the folders' issue the script expects the structure that is created by the transfer_fast5_to_server.py which is bunch of  .tar.gz files in the fast5 folder.

I will update that such that if there is no "TRANSFERRING" lock file and no directories complete then it should throw an error.
